
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 16 03:23:06 CET 2020
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int RETOURNE = 20;
  public static final int IDF = 32;
  public static final int OP_EQUAL = 27;
  public static final int CSTENTIERE = 33;
  public static final int OP_AND = 29;
  public static final int LIRE = 7;
  public static final int EQUAL = 9;
  public static final int OP_LESS = 26;
  public static final int ECRIRE = 8;
  public static final int FONCTION = 19;
  public static final int TANTQUE = 10;
  public static final int ALORS = 14;
  public static final int OP_NOT = 31;
  public static final int OP_PLUS = 21;
  public static final int VIRGULE = 6;
  public static final int OP_OR = 30;
  public static final int REPETER = 11;
  public static final int OP_NEQUAL = 28;
  public static final int OP_MULTIPLY = 23;
  public static final int POINTVIRGULE = 5;
  public static final int FINTANTQUE = 12;
  public static final int SINON = 15;
  public static final int PARA_CLOSE = 18;
  public static final int TYPE = 34;
  public static final int OP_GREATER = 25;
  public static final int OP_MINUS = 22;
  public static final int EOF = 0;
  public static final int SI = 13;
  public static final int error = 1;
  public static final int PARA_OPEN = 17;
  public static final int OP_DIVIDE = 24;
  public static final int DEBUT = 3;
  public static final int FINSI = 16;
  public static final int FIN = 4;
  public static final int PROGRAMME = 2;
}

