
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 10 18:08:14 CET 2020
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 29;
  public static final int OP_EQUAL = 24;
  public static final int CSTENTIERE = 30;
  public static final int OP_AND = 26;
  public static final int LIRE = 6;
  public static final int EQUAL = 8;
  public static final int OP_LESS = 23;
  public static final int ECRIRE = 7;
  public static final int TANTQUE = 9;
  public static final int ALORS = 13;
  public static final int OP_NOT = 28;
  public static final int OP_PLUS = 18;
  public static final int OP_OR = 27;
  public static final int REPETER = 10;
  public static final int OP_NEQUAL = 25;
  public static final int OP_MULTIPLY = 20;
  public static final int POINTVIRGULE = 5;
  public static final int FINTANTQUE = 11;
  public static final int SINON = 14;
  public static final int PARA_CLOSE = 17;
  public static final int TYPE = 31;
  public static final int OP_GREATER = 22;
  public static final int OP_MINUS = 19;
  public static final int EOF = 0;
  public static final int SI = 12;
  public static final int error = 1;
  public static final int PARA_OPEN = 16;
  public static final int OP_DIVIDE = 21;
  public static final int DEBUT = 3;
  public static final int FINSI = 15;
  public static final int FIN = 4;
  public static final int PROGRAMME = 2;
}

