
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 08 02:00:50 CET 2020
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 16;
  public static final int CSTENTIERE = 17;
  public static final int LIRE = 6;
  public static final int EQUAL = 8;
  public static final int ECRIRE = 7;
  public static final int TANTQUE = 9;
  public static final int ALORS = 13;
  public static final int REPETER = 10;
  public static final int POINTVIRGULE = 5;
  public static final int FINTANTQUE = 11;
  public static final int SINON = 14;
  public static final int TYPE = 18;
  public static final int EOF = 0;
  public static final int SI = 12;
  public static final int error = 1;
  public static final int DEBUT = 3;
  public static final int FINSI = 15;
  public static final int FIN = 4;
  public static final int PROGRAMME = 2;
}

